title: Girlguiding - Hertfordshire County
url: https://www.girlguidinghertfordshire.org.uk
twitter:
  username: gguidingherts
  card: summary
social:
  links:
    - https://twitter.com/gguidingherts
    - https://www.linkedin.com/company/girlguiding-herts/
    - https://www.facebook.com/GirlguidingHertfordshire
logo: /assets/images/core/herts-logo.jpg
locale: en_GB
collections:
    posts:
      permalink: /news/:title/
    events:
      output: true
      permalink: /event/:title/
      sort_by: event.start_date
    fundraising_ideas:
      output: true
      permalink: /about-us/county-centre/fundraising/ideas/:title/
    trainingevents:
      output: true
      permalink: /training/:title/
      sort_by: event.start_date
    noticeboards:
      output: true
      permalink: /noticeboard/:title/
    members:
      output: false
      permalink: /about-us/county-team/:title/
    shops_nights:
      output: true
      sort_by: title
      permalink: /shops-nights/:title/
    membership_updates:
      output: false
    adverts:
      output: false
    bighelpout:
      output: true
      permalink: /big-help-out/:title
    vacancies:
      output: false
    inspire:
      output: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-v5"
      advertId: "get-involved"
      toc: "news"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event-v5"
      toc: "events"
  - scope:
      path: ""
      type: "fundraising_ideas"
    values:
      layout: "page-v5"
      toc: "about-us"
  - scope:
      path: ""
      type: "trainingevents"
    values:
      layout: "event-v5"
      toc: "training"
  - scope:
      path: ""
      type: "noticeboards"
    values:
      layout: "post-v5"
      image_filter: true
      toc: "news"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "county_team"
      toc: "about-us"
  - scope:
      path: ""
      type: "shops_nights"
    values:
      layout: "shops_nights"
      toc: "about-us"
      location_map: true
      county: "Hertfordshire"
      showmap: true
  - scope:
      path: ""
      type: "bighelpout"
    values:
      layout: "page-v5"
      toc: "news"
  - scope:
      path: ""
      type: "vacancies"
    values:
      button_text: "Role description"
email:
  base_url: "https://email.girlguidinghertfordshire.org.uk/api/"
  apikey: "OifYW6lBBY3CUykd9NhfBeojO8aAYWhdHiJaDa8RFm8="
recaptcha:
  sitekey: "6LeUzcQbAAAAAMu_4Jr8oMO_e-i1R3_bF0y08BRk"
include: 
  - _redirects