collections:
    events:
      output: true
      permalink: /event/:title/
      sort_by: event.start_date
    noticeboards:
      output: true
      permalink: /noticeboard/:title/
    members:
      output: true
      permalink: /about-us/county-team/:title/
      sort_by: order
    shops_nights:
      output: true
      sort_by: title
      permalink: /shops-nights/:title/
    membership_updates:
    adverts:
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "noticeboards"
    values:
      layout: "noticeboard"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "county_team"
      toc: "about-us"
  - scope:
      path: ""
      type: "shops_nights"
    values:
      layout: "shops_nights"
      toc: "about-us"
      county: "Hertfordshire"
email:
  base_url: "https://email.girlguidinghertfordshire.org.uk/api/"
  apikey: "OifYW6lBBY3CUykd9NhfBeojO8aAYWhdHiJaDa8RFm8="
recaptcha:
  sitekey: "6LeUzcQbAAAAAMu_4Jr8oMO_e-i1R3_bF0y08BRk"
include: 
  - _redirects