title: Girlguiding - Hertfordshire County
url: https://www.girlguidinghertfordshire.org.uk
twitter:
  username: gguidingherts
  card: summary
logo: /assets/images/core/logo.png
locale: en_GB
collections:
    posts:
      permalink: /news/:title/
    events:
      output: true
      permalink: /event/:title/
      sort_by: event.start_date
    trainingevents:
      output: true
      permalink: /training/:title/
      sort_by: event.start_date
    noticeboards:
      output: true
      permalink: /noticeboard/:title/
    members:
      output: false
      permalink: /about-us/county-team/:title/
    shops_nights:
      output: true
      sort_by: title
      permalink: /shops-nights/:title/
    membership_updates:
    adverts:
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-v5"
      advertId: "get-involved"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event-v5"
  - scope:
      path: ""
      type: "trainingevents"
    values:
      layout: "event-v5"
  - scope:
      path: ""
      type: "noticeboards"
    values:
      layout: "post-v5"
      image_filter: true
  - scope:
      path: ""
      type: "members"
    values:
      layout: "county_team"
      toc: "county-teams"
      is_employee: false
  - scope:
      path: ""
      type: "shops_nights"
    values:
      layout: "shops_nights"
      toc: "about-us"
      location_map: true
      county: "Hertfordshire"
      showmap: true
email:
  base_url: "https://email.girlguidinghertfordshire.org.uk/api/"
  apikey: "OifYW6lBBY3CUykd9NhfBeojO8aAYWhdHiJaDa8RFm8="
recaptcha:
  sitekey: "6LeUzcQbAAAAAMu_4Jr8oMO_e-i1R3_bF0y08BRk"
include: 
  - _redirects